// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/proto/audiostrippersvc/v1/audiostrippersvc.proto

package proto_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message to represent chunks of video data being sent to the server.
type VideoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleRate string `protobuf:"bytes,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Data       []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *VideoData) Reset() {
	*x = VideoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoData) ProtoMessage() {}

func (x *VideoData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoData.ProtoReflect.Descriptor instead.
func (*VideoData) Descriptor() ([]byte, []int) {
	return file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescGZIP(), []int{0}
}

func (x *VideoData) GetSampleRate() string {
	if x != nil {
		return x.SampleRate
	}
	return ""
}

func (x *VideoData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message to represent chunks of audio data being sent back to the client.
type AudioData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AudioData) Reset() {
	*x = AudioData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioData) ProtoMessage() {}

func (x *AudioData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioData.ProtoReflect.Descriptor instead.
func (*AudioData) Descriptor() ([]byte, []int) {
	return file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescGZIP(), []int{1}
}

func (x *AudioData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_proto_audiostrippersvc_v1_audiostrippersvc_proto protoreflect.FileDescriptor

var file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDesc = []byte{
	0x0a, 0x34, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x70, 0x65, 0x72, 0x73, 0x76, 0x63, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x70, 0x65, 0x72, 0x73, 0x76, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x3b, 0x0a, 0x0d, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x70, 0x70, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x0c, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x0a, 0x2e, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0a, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x61,
	0x74, 0x61, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x73, 0x72, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x73, 0x74, 0x72, 0x69, 0x70, 0x70, 0x65, 0x72, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescOnce sync.Once
	file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescData = file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDesc
)

func file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescGZIP() []byte {
	file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescOnce.Do(func() {
		file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescData)
	})
	return file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDescData
}

var file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_goTypes = []interface{}{
	(*VideoData)(nil), // 0: VideoData
	(*AudioData)(nil), // 1: AudioData
}
var file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_depIdxs = []int32{
	0, // 0: AudioStripper.ExtractAudio:input_type -> VideoData
	1, // 1: AudioStripper.ExtractAudio:output_type -> AudioData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_init() }
func file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_init() {
	if File_api_proto_audiostrippersvc_v1_audiostrippersvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_goTypes,
		DependencyIndexes: file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_depIdxs,
		MessageInfos:      file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_msgTypes,
	}.Build()
	File_api_proto_audiostrippersvc_v1_audiostrippersvc_proto = out.File
	file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_rawDesc = nil
	file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_goTypes = nil
	file_api_proto_audiostrippersvc_v1_audiostrippersvc_proto_depIdxs = nil
}
