version: "3"

tasks:
  proto:
    desc: "Generate protobuf server files"
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/proto/audiostrippersvc/v1/*.proto
